#!/usr/bin/env python3
"""Repository-native Wright-Fisher benchmark for the focal RNA system.

This is a refactoring of the count-level runner used for the frozen reference
run. It consumes the NC nodes and analytic predictions generated by
joint_portal_model.py. The core Wright-Fisher update is unchanged in meaning:
fitness-weighted multinomial parent sampling followed by independent per-site
mutation, including rare multi-substitution offspring.

The scoring event is a threshold-based takeover proxy: when resident phenotype
p0 first falls below 25% of the population, the dominant phenotype is recorded.
This is used as a computational proxy for which adaptive phenotype fixes first;
it is not literal observation of complete fixation.
"""
import argparse, json, math, sys
from collections import Counter
from pathlib import Path
import numpy as np
from rna_gp import FoldCache

BASES='ACUG'; L=12
P0,P1,P2=19529749,27262981,27918661
N=500; MU=2e-5; S1=0.005; S2=[0.01,0.02,0.04,0.08,0.16,0.32]

def mutate_one(seq,cat):
    pos=cat//3; j=cat%3; alts=[b for b in BASES if b!=seq[pos]]
    return seq[:pos]+alts[j]+seq[pos+1:]

def mutation_count_weights(mu):
    w=np.array([math.comb(L,d)*mu**d*(1-mu)**(L-d) for d in range(L+1)],float); return w/w.sum()

def mutate_multi(seq,d,rng):
    s=list(seq)
    for pos in rng.choice(L,size=d,replace=False):
        alts=[b for b in BASES if b!=s[pos]]; s[pos]=alts[int(rng.integers(0,3))]
    return ''.join(s)

def reproduce(pop,cache,fitness,N,mu,rng,hd):
    live=[]; weights=[]
    for seq,count in pop.items():
        fit=fitness.get(cache.get(seq),0.0)
        if count>0 and fit>0: live.append(seq); weights.append(count*fit)
    if not weights: return Counter()
    probs=np.asarray(weights,float); probs/=probs.sum(); parent_counts=rng.multinomial(N,probs)
    out=Counter(); q0,q1=float(hd[0]),float(hd[1]); qm=float(hd[2:].sum())
    for seq,n in zip(live,parent_counts):
        n=int(n)
        if not n: continue
        n0,n1,nm=rng.multinomial(n,[q0,q1,qm]); out[seq]+=int(n0)
        if n1:
            cats=rng.multinomial(int(n1),np.full(36,1/36))
            for cat,c in enumerate(cats):
                if c: m=mutate_one(seq,cat); cache.get(m); out[m]+=int(c)
        if nm:
            cond=hd[2:]/qm
            for dd in rng.choice(np.arange(2,L+1),size=int(nm),p=cond):
                m=mutate_multi(seq,int(dd),rng); cache.get(m); out[m]+=1
    if sum(out.values())!=N: raise RuntimeError('offspring count mismatch')
    return out

def phenotype_counts(pop,cache):
    out=Counter()
    for seq,n in pop.items(): out[cache.get(seq)]+=int(n)
    return out

def relax(start,cache,rng,hd):
    pop=Counter({start:N}); fit={P0:1.0}
    for _ in range(10*N): pop=reproduce(pop,cache,fit,N,MU,rng,hd)
    return Counter({s:n for s,n in pop.items() if cache.get(s)==P0})

def adaptive(pop,cache,s2,rng,hd,T=10_000_000):
    fit={P0:1.0,P1:1.0+S1,P2:1.0+s2}
    for step in range(T):
        pop=reproduce(pop,cache,fit,N,MU,rng,hd); pc=phenotype_counts(pop,cache)
        if pc.get(P0,0)<0.25*N:
            if not pc: return -1,step
            # Keep the historical scoring rule used by the frozen reference:
            # record the dominant phenotype at the resident <25% threshold.
            return int(max(pc.items(),key=lambda kv:kv[1])[0]),step
    return -1,T

def wilson(k,n,z=1.959963984540054):
    if n <= 0:
        return [None,None]
    p=k/n; den=1+z*z/n; cen=(p+z*z/(2*n))/den; half=z*math.sqrt(p*(1-p)/n+z*z/(4*n*n))/den
    return [cen-half,cen+half]

def main():
    ap=argparse.ArgumentParser(); ap.add_argument('--workdir',default='.'); ap.add_argument('--reps',type=int,default=1000); ap.add_argument('--seed',type=int,default=20260823); ap.add_argument('--force-relax',action='store_true'); ap.add_argument('--force-conditions',action='store_true'); args=ap.parse_args()
    root=Path(args.workdir).resolve(); results=root/'results'; results.mkdir(exist_ok=True)
    nodes_path=results/'nc_nodes.json'; analytic_path=results/'analytic_predictions_N500.json'
    if not nodes_path.exists() or not analytic_path.exists(): raise SystemExit('Run src/joint_portal_model.py first.')
    nodes=json.loads(nodes_path.read_text(encoding='utf-8')); cache=FoldCache(results/'rna_fold_cache.json')
    if len(nodes)!=1937: raise RuntimeError(f'expected 1937 focal NC nodes, got {len(nodes)}')
    amap={float(r['s2']):r for r in json.loads(analytic_path.read_text(encoding='utf-8'))['results']}
    hd=mutation_count_weights(MU); reps=args.reps
    print(f'PRECHECK N={N} mu={MU} reps={reps} p0_nodes={len(nodes)} P(>=2 subs)={hd[2:].sum():.12g}')
    relax_path=results/f'wf_relaxed_reps{reps}_seed{args.seed}.json'
    if relax_path.exists() and not args.force_relax:
        relaxed=[Counter({k:int(v) for k,v in x.items()}) for x in json.loads(relax_path.read_text(encoding='utf-8'))]; print(f'RELAX resume {len(relaxed)}')
    else:
        relaxed=[]; seeds=np.random.SeedSequence(args.seed).spawn(reps)
        for i,ss in enumerate(seeds):
            rng=np.random.default_rng(ss); start=nodes[int(rng.integers(0,len(nodes)))]; relaxed.append(relax(start,cache,rng,hd))
            if (i+1)%50==0 or i==0: print(f'RELAX {i+1}/{reps}',flush=True); cache.save()
        relax_path.write_text(json.dumps([dict(x) for x in relaxed]),encoding='utf-8'); cache.save()
    outrows=[]
    for ci,s2 in enumerate(S2):
        cp=results/f'wf_condition_s2_{str(s2).replace(".","p")}_reps{reps}_seed{args.seed}.json'
        if cp.exists() and not args.force_conditions: r=json.loads(cp.read_text(encoding='utf-8')); outrows.append(r); print(f'S2={s2} resumed'); continue
        seeds=np.random.SeedSequence([args.seed,1000+ci]).spawn(reps); wins=[]; times=[]
        for i,ss in enumerate(seeds):
            w,t=adaptive(relaxed[i].copy(),cache,s2,np.random.default_rng(ss),hd); wins.append(w); times.append(t)
            if (i+1)%50==0 or i==0: print(f'S2={s2:.3f} {i+1}/{reps} p2={sum(x==P2 for x in wins)}',flush=True); cache.save()
        succ=sum(w in (P1,P2) for w in wins); p2=sum(w==P2 for w in wins); y=(p2/succ if succ else None)
        a=amap[s2]
        r={'s2':s2,'reps':reps,'successful_p1_or_p2':succ,'p1_wins':sum(w==P1 for w in wins),'p2_wins':p2,'other_or_timeout':reps-succ,'wf_p2_takeover_proxy':y,'wf_p2_first':y,'wf_p2_first_wilson95':wilson(p2,succ),'mean_takeover_step_success':float(np.mean([t for w,t in zip(wins,times) if w in (P1,P2)])),'mean_fixation_step_success':float(np.mean([t for w,t in zip(wins,times) if w in (P1,P2)])),'average_rate_p2_first':a['average_rate_p2_first'],'Martin2024_burst_aware_p2_first':a['Martin2024_burst_aware_p2_first'],'joint_p2_first':a['joint_p2_first']}
        cp.write_text(json.dumps(r,indent=2),encoding='utf-8'); outrows.append(r); cache.save()
    payload={'experiment':'JOINT_PORTAL_RNA_WRIGHT_FISHER_TAKEOVER_BENCHMARK_V2','parameters':{'N':N,'mu':MU,'s1':S1,'s2':S2,'reps':reps,'seed':args.seed},'results':outrows}
    out=results/f'wf_direct_reps{reps}_result.json'; out.write_text(json.dumps(payload,indent=2),encoding='utf-8'); cache.save()
    print(f'FINAL=PASS_WRIGHT_FISHER_DIRECT_COMPARISON_COMPLETE\nRESULT_JSON={out}')
if __name__=='__main__': main()
